apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: basic-ingress
spec:
  backend:
    - path: /*
      backend:
        serviceName: polling-app-client
        servicePort: 80
    - path: /api/*
        backend:
        serviceName: polling-app-server
        servicePort: 8080
---